// ---------------------------------------------------------------------
// New library: the only content source for Daily (from its start date) and
// Systems. 3 Minutes and Race never read this module (see timedLibrary.js).
// ---------------------------------------------------------------------
// Everything served here is fixed in src/data/library/newLibrary.js, which is
// generated by scripts/library/activate.mjs and checked into the repo:
//   • starter boards: five per subject (fewer where content ran short)
//   • the Daily schedule: one reviewed board per day from `dailyStart`
//   • Systems expansion boards: built only from released Daily connections,
//     each with the Daily day it unlocks on
// Nothing is generated at runtime, so the same date or board id gives every
// player on every device the same puzzle, and a refresh or a later import can
// never move a published board.
import NEW_LIBRARY from '../data/library/newLibrary.js'
import { dayIndex } from './calendar.js'
import { dayNumber } from './game.js'

export const NEW_DAILY_START = NEW_LIBRARY.dailyStart
export const LIBRARY_SUBJECTS = NEW_LIBRARY.subjects

// Display names. "Biochemistry/Genetics" keeps its id (player progress is keyed
// by it) but reads as Biochemistry now that Genetics is its own subject.
const LABELS = { 'Biochemistry/Genetics': 'Biochemistry' }
export const subjectLabel = (s) => LABELS[s] || s

export const getLibraryConnection = (id) => NEW_LIBRARY.connections[id] || null
export const libraryConnections = () => Object.values(NEW_LIBRARY.connections)

const TIER = { easy: 0, medium: 1, hard: 2, expert: 3 }
const cap = (s) => (s ? s.charAt(0).toUpperCase() + s.slice(1) : '')

// Day offset of a date key from the start of the new Daily (negative before).
export const libraryDay = (key) => dayIndex(key) - dayIndex(NEW_DAILY_START)
export const isNewLibraryDate = (key) => key >= NEW_DAILY_START

// Turns four library connections into the playable puzzle shape. Colours come
// from the board itself: groups are ordered easiest to hardest by their own
// difficulty (ties keep board order) and take levels 1 to 4, so a board with
// two Easy groups still shows four distinct colours, and each group keeps
// its real difficulty label. No text is added: tiles have no per-tile note
// and there is no "remember" line unless the source row had one.
export function buildLibraryPuzzle(ids, meta) {
  const conns = ids.map((id) => NEW_LIBRARY.connections[id])
  if (conns.length !== 4 || conns.some((c) => !c)) return null
  const ordered = conns
    .map((c, i) => ({ c, i }))
    .sort((a, b) => (TIER[a.c.difficulty] ?? 9) - (TIER[b.c.difficulty] ?? 9) || a.i - b.i)
    .map((x) => x.c)
  const categories = ordered.map((c, i) => ({
    level: i + 1,
    difficulty: c.difficulty,
    difficultyLabel: cap(c.difficulty),
    title: c.title,
    explanation: c.explanation,
    remember: '',
    connectionType: c.connectionType,
    tags: [],
    bankCategoryId: c.id,
    canonicalId: c.canonicalId,
    library: 'new',
    review: c.review,
    items: c.tiles.map((term) => ({ term, why: '' })),
  }))
  return {
    id: meta.id,
    number: meta.number,
    type: meta.type,
    date: meta.date || null,
    title: meta.title,
    systems: [...new Set(ordered.map((c) => c.subject))],
    topicTags: [],
    status: 'published',
    source: 'Plexus library (reviewed connections)',
    library: 'new',
    boardId: meta.boardId,
    categories,
  }
}

// ---- Daily ----
// Day n plays schedule board n. After the last board the schedule replays
// from the first, in the same order (the exhaustion policy), so a date never
// lacks a reviewed puzzle and nothing unreviewed is ever generated.
export function dailyBoardForDate(key) {
  const n = libraryDay(key)
  const boards = NEW_LIBRARY.dailyBoards
  if (n < 0 || boards.length === 0) return null
  return { board: boards[n % boards.length], cycle: Math.floor(n / boards.length) + 1, day: n }
}

export function getNewDailyPuzzle(key) {
  const slot = dailyBoardForDate(key)
  if (!slot) return null
  const puzzle = buildLibraryPuzzle(slot.board.ids, {
    id: `daily-${key}`,
    number: dayNumber(key),
    type: 'daily',
    date: key,
    title: 'Daily Plexus',
    boardId: slot.board.id,
  })
  if (puzzle) puzzle.cycle = slot.cycle
  return puzzle
}

export const dailyRunwayEnd = () => {
  const n = NEW_LIBRARY.dailyBoards.length
  return n ? n - 1 : -1
}

// ---- Systems ----
// The boards a subject offers on `todayKey`: its starter boards, then every
// expansion board whose Daily has been released on or before that date.
export function systemsBoardsFor(subject, todayKey) {
  const starter = (NEW_LIBRARY.starterBoards[subject] || []).map((b) => ({ ...b, subject, kind: 'starter' }))
  const day = libraryDay(todayKey)
  const more = NEW_LIBRARY.expansionBoards
    .filter((b) => b.subject === subject && b.releaseDay <= day)
    .map((b) => ({ ...b, kind: 'more' }))
  return [...starter, ...more]
}

export function systemsBoardPuzzle(board, index) {
  return buildLibraryPuzzle(board.ids, {
    id: board.id,
    number: index + 1,
    type: 'system',
    title: subjectLabel(board.subject),
    boardId: board.id,
  })
}

// Every connection id the new library can serve, for lookups (mastery,
// backfill). Read-only.
export const libraryConnectionMap = () => NEW_LIBRARY.connections

// A subject's Systems state for one player: the boards available today, how
// many they have finished, and the next unfinished board (null = caught up).
export function subjectProgress(subject, todayKey, finished = {}) {
  const boards = systemsBoardsFor(subject, todayKey)
  const completed = boards.filter((b) => finished[b.id]).length
  const i = boards.findIndex((b) => !finished[b.id])
  return { subject, boards, total: boards.length, completed, next: i >= 0 ? { board: boards[i], index: i } : null }
}

export const CAUGHT_UP_COPY = 'You’re caught up! Check back for more puzzles soon.'
