// ---------------------------------------------------------------------
// Timed library: the only content source for 3 Minutes and Race.
// ---------------------------------------------------------------------
// The existing connection bank minus every entry removed at activation
// (src/data/library/timedLibrary.js, generated by
// scripts/library/activate.mjs):
//   • confirmed equivalents of new-library connections (removed for good)
//   • entries with an unresolved overlap against active new-library content
//     (excluded until that pair is decided)
// It never reads the new library and nothing here falls back to it. The bank
// is a static module, so two Race players with the same code always build
// from the identical list.
import connectionBank from '../data/connectionBank.js'
import { TIMED_EXCLUSIONS, TIMED_CANONICAL } from '../data/library/timedLibrary.js'

export const timedBank = connectionBank.filter((c) => !TIMED_EXCLUSIONS[c.id])

export const isTimedExcluded = (id) => !!TIMED_EXCLUSIONS[id]

// Canonical relationship id for a timed entry: entries the audit found to be
// the same relationship share one id, so a session never serves both.
export const timedCanonicalId = (id) => TIMED_CANONICAL[id] || id
