// Regenerates src/data/generatedPuzzles.js from the connection bank
// (src/data/connectionBank.js) using the puzzle assembler
// (src/utils/puzzleAssembler.js). Deterministic (seeded) so re-running it
// without bank changes reproduces the same output.
//
// Run with: node scripts/assemblePuzzles.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import connectionBank from '../src/data/connectionBank.js'
import { autoGeneratePuzzles } from '../src/utils/puzzleAssembler.js'
import { validatePuzzle } from '../src/puzzles.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

const SEED = 20260919 // fixed seed -> reproducible content
const COUNT = 6

const puzzles = autoGeneratePuzzles(connectionBank, { count: COUNT, seed: SEED, startNumber: 1 })

console.log(`Generated ${puzzles.length} puzzle(s) from the connection bank:\n`)

let anyInvalid = false
for (const p of puzzles) {
  const errors = validatePuzzle(p)
  const bankIds = p.categories.map((c) => c.bankCategoryId).join(', ')
  console.log(`- ${p.id}  "${p.title}"`)
  console.log(`    systems: ${p.systems.join(', ')}`)
  console.log(`    from bank categories: ${bankIds}`)
  if (errors.length) {
    anyInvalid = true
    console.log(`    INVALID: ${errors.join('; ')}`)
  }
}

const verifiedCount = connectionBank.filter((c) => c.status === 'verified').length
const needsReview = connectionBank.filter((c) => c.status !== 'verified')
console.log(`\nBank: ${connectionBank.length} categories total, ${verifiedCount} verified.`)
if (needsReview.length) {
  console.log(`needs_review / rejected (excluded from generation): ${needsReview.map((c) => c.id).join(', ')}`)
}

if (anyInvalid) {
  console.error('\nOne or more generated puzzles failed validatePuzzle — NOT writing output.')
  process.exit(1)
}

const header = `// AUTO-GENERATED by scripts/assemblePuzzles.mjs — do not hand-edit.
// Regenerate with: node scripts/assemblePuzzles.mjs
// Source content lives in src/data/connectionBank.js; this file is just
// the assembler's output, wired into the existing puzzle system exactly
// like any other src/data/systemPuzzles.js entry.
`

const body = `${header}\nconst generatedPuzzles = ${JSON.stringify(puzzles, null, 2)}\n\nexport default generatedPuzzles\n`

const outPath = path.join(__dirname, '..', 'src', 'data', 'generatedPuzzles.js')
fs.writeFileSync(outPath, body)
console.log(`\nWrote ${puzzles.length} puzzle(s) to ${path.relative(process.cwd(), outPath)}`)
